name: Deploy insight-fe

on:
  push:
    branches: [develop, qa]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: Neonbee-ai/neonbee-devops/.github/workflows/neonbee-deploy-vite-mfe.yml@main
    with:
      service_name: insight-fe
      nginx_root_dev: /var/www/dev.insight.skyoffice360.com/html
      nginx_root_staging: /var/www/staging.insight.skyoffice360.com/html
      vite_base_url_dev: https://dev.insight.skyoffice360.com/
      vite_base_url_staging: https://staging.insight.skyoffice360.com/
    secrets: inherit