name: Deploy Insight Frontend

on:
  push:
    branches: [develop, qa]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: Neonbee-ai/neonbee-devops/.github/workflows/neonbee-deploy-vite-mfe.yml@main
    with:
      service_name: insight-fe
      nginx_root_dev: /var/www/dev-cdn.skyoffice360.com/html/insight
      nginx_root_staging: /var/www/staging.insight.skyoffice360.com/html
      vite_base_url_dev: https://dev-cdn.skyoffice360.com/insight/
      vite_base_url_staging: https://staging.insight.skyoffice360.com/
      is_mfe: true
    secrets: inherit
